name: Build Wiki

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build Docs
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
          submodules: true

      - name: Build
        run: |
          cd docs
          python ./generate.py

      - name: Publish
        uses: Andrew-Chen-Wang/github-wiki-action@v2
        env:
          WIKI_DIR: docs/overlunky.wiki/
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_MAIL: fake.user@github.com
          GH_NAME: Build-Wiki-Bot
